# Generated by Django 3.0.3 on 2020-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshe', '0002_auto_20200830_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookType', models.CharField(max_length=20)),
            ],
        ),
    ]
