# Generated by Django 3.0.3 on 2020-08-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keshe', '0004_book_b_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keshe.BookType'),
        ),
    ]
