# Generated by Django 3.0.3 on 2020-08-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshe', '0005_auto_20200830_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='borrow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='borrow',
            field=models.IntegerField(default=0),
        ),
    ]
